//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMPH
    {
        public System.DateTime Data { get; set; }
        public int Posto { get; set; }
        public int Vaz_nat { get; set; }
        public int Vaz_Inc { get; set; }
        public decimal Reserv { get; set; }
        public System.DateTime Data_Update { get; set; }
    }
}
